// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Oracle.EntityFrameworkCore.Metadata;
using Sprint1.Data;

#nullable disable

namespace Sprint1.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20251105115338_FIAP")]
    partial class FIAP
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            OracleModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Sprint1.Models.Produto", b =>
                {
                    b.Property<int>("Produto_ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("PRODUTO_ID");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Produto_ID"));

                    b.Property<decimal>("Avaliacao_media")
                        .HasColumnType("DECIMAL(18, 2)")
                        .HasColumnName("AVALIACAO_MEDIA");

                    b.Property<string>("Categoria")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)")
                        .HasColumnName("CATEGORIA");

                    b.Property<string>("Condicao_produto")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)")
                        .HasColumnName("CONDICAO_PRODUTO");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)")
                        .HasColumnName("DESCRICAO");

                    b.Property<string>("Dimensoes")
                        .HasColumnType("NVARCHAR2(2000)")
                        .HasColumnName("DIMENSOES");

                    b.Property<int>("Estoque")
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("ESTOQUE");

                    b.Property<string>("Idioma")
                        .HasColumnType("NVARCHAR2(2000)")
                        .HasColumnName("IDIOMA");

                    b.Property<string>("Imagem_url")
                        .HasColumnType("NVARCHAR2(2000)")
                        .HasColumnName("IMAGEM_URL");

                    b.Property<int>("Numero_de_avaliacoes")
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("NUMERO_DE_AVALIACOES");

                    b.Property<decimal?>("Peso")
                        .HasColumnType("decimal(10, 2)")
                        .HasColumnName("PESO");

                    b.Property<decimal?>("Preco_descontado")
                        .HasColumnType("decimal(10, 2)")
                        .HasColumnName("PRECO_DESCONTADO");

                    b.Property<decimal>("Preco_original")
                        .HasColumnType("decimal(10, 2)")
                        .HasColumnName("PRECO_ORIGINAL");

                    b.Property<string>("Titulo")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)")
                        .HasColumnName("TITULO");

                    b.HasKey("Produto_ID");

                    b.ToTable("PRODUTOS");
                });
#pragma warning restore 612, 618
        }
    }
}
